[theme]
primaryColor = "#4F46E5"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#F8FAFC"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
